config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"
  get "home/about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pie = Order.group(:currency).sum(:total)
    @month_sales = Order.group(:Month).sum(:total)
    @goals = Order
    @top_city = Order.group(:bill_city).limit(10).order('total DESC').sum(:total)
    @top_products = Order.group(:product_name).limit(10).order('total DESC').sum(:total)
    @returned = Order.where(:payment_state =='refunded').group(:product_name).limit(10).order('total DESC').sum(:total)
    # @top_city = Order.sum(
    # :group => 'bill_city',
    # :order => 'SUM(total) DESC',
    # :limit => 10)
    puts Order.group(:bill_city).sum(:total).first
  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1> About</h1>

app/views/home/index.html.erb
<h2>Plot</h2>
<% if user_signed_in? %>
<%= column_chart Order.group(:bill_country_iso_name).sum(:total), title: "Country sales", xtitle: "Country", ytitle: "Sales"%>
</br></br>
<%= column_chart @month_sales, title: "Monthly Sales", xtitle: "Month", ytitle: "Sales"%>
</br></br>
<%= pie_chart @pie, title: "Currecy Used" %>
</br>
</br>
<%= line_chart Order.group(:completed_at_y).sum(:total) ,title: "Timeline sales" %>

<%= column_chart Order.group(:Year).sum(:total),title: "Yearly Sales", xtitle: "Year", ytitle: "Sales" %>

</br>
<%= column_chart Order.group(:Hour).sum(:total),title: "Peak Hour Sales", xtitle: "Hour", ytitle: "Sales" %>

</br>
<%= column_chart Order.group(:DayofWeek).sum(:total),title: "Day of Week Sales", xtitle: "Day of Week", ytitle: "Sales" %>

</br>
<%= column_chart @top_city,title: "Top City for Sales", xtitle: "City", ytitle: "Sales", stacked: true %>

</br>
<%= column_chart @top_products  ,title: "Top Products Sold", xtitle: "Product Name", ytitle: "Sales", stacked: true %>

</br>
<%= column_chart @returned ,title: "Most Returned Products", xtitle: "Product Name", ytitle: "Sales", stacked: true %>

</br>

</br>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<h5>Country Sales</h5>

<%= geo_chart Order.group(:bill_country_iso_name).count %>

<% else %>

<h1>Please Sign In to see the graphs</h1>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "U-Exposed", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active"%>
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link active"%>
        </li>
        <li class="nav-item">

          <%=  link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", user_session_path, class:"nav-link active"%>
        </li>
        <% end %>
        <li class="nav-item">

          <%=  link_to 'About', home_about_path, class:"nav-link"%>
        </li>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <title>Papp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <div class = "container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header"%>
    <%= yield %>
    </div>
    </body>
</html>